### ISSUE TITLE
import-aws doesn't work with latest apache-libcloud (0.15.1)

### ISSUE THREAD

**Issue by monkey1016** [shinken-monitoring/mod-import-aws#7]
When using the latest version of apache-libcloud, launching the module will result in this error:

[1413396893] Info :    I correctly loaded the modules: [named-pipe,pickle-retention-file,AWS]
[1413396894] Error :   Instance AWS raised an exception 'Node' object has no attribute 'private_ip'. Log and continue to run
[1413396894] Error :   Back trace of this remove: Traceback (most recent call last):

```
  File "/usr/local/lib/python2.7/dist-packages/shinken/daemons/arbiterdaemon.py", line 327, in load_config_file
    r = inst.get_objects()
  File "/var/lib/shinken/modules/import-aws/module.py", line 118, in get_objects
    h['_EC2_PRIVATE_IP'] = unicode(n.private_ip[0])
AttributeError: 'Node' object has no attribute 'private_ip'
```

The `Node` object contains an attribute called `private_ips` which is a list.  The same issue occurs with `public_ip`.
